### ISSUE TITLE
Using medium-editor-list with angular does not load

### ISSUE THREAD

**Issue by josefromsanjose** [mkawczynski07/medium-editor-list#2]
I am using MediumEditor angular and I am looking to add your extension to support lists. I came across an issue when it is part of a directive. 

In the following function:

```
getExistsingLists: function () {
        var $lists = this.editor.origElements.querySelector('ul.' + MEDIUM_EDITOR_CLASS);
        return isDefined($lists) ? $lists : [];
    },
```

`this.originalElements` returns in DOM element itself, but in Angular it returns an object where the element is found at index:0. 
**Solution:**

```
getExistsingLists: function () {
        var $lists = this.editor.origElements[0]
            ? this.editor.origElements[0].querySelector('ul.' + MEDIUM_EDITOR_CLASS)
            : this.editor.origElements.querySelector('ul.' + MEDIUM_EDITOR_CLASS);
        return isDefined($lists) ? $lists : [];
    },
```

This continues to with and without of Angular.

**Comment by mkawczynski07** [comment]
Thanks. Good job. :) I merged your pull requests.
