### ISSUE TITLE
getExistsingLists and querySelector are not function

### ISSUE THREAD

**Issue by ct1735x** [mkawczynski07/medium-editor-list#8]
The code himself works and the list is properly rendered on medium editor.
But console shows two JS errors, the first one on load : 
```
medium-editor-list-min.js:1 Uncaught TypeError: this.getExistsingLists is not a function
    at c.initExistsingLists (medium-editor-list-min.js:1)
    at medium-editor-list-min.js:1
```

The second one is shown when a list is created : 
```
ncaught TypeError: P.querySelector is not a function
    at s.a [as create] (medium-editor-list-min.js:1)
    at c.onClick
```

**Comment by ct1735x** [comment]
First issue is due to a tippo in the source code (getExi**sts**ing instead of getExisting)
Still searching for the second one

**Comment by mkawczynski07** [comment]
Feel free to make a pull request :)  Frankly, I was working on this 5 years ago... But I can merge the pull and build a version with fixes.

**Comment by ct1735x** [comment]
I will
`Uncaught TypeError: this.editor.origElements.querySelector is not a function`
Don't you have any idea where this could come from ?
My JS abilities are limited

**Comment by mkawczynski07** [comment]
I think that when I was developing it was a reference to elements that ME is monitoring. Now there is a method: [https://github.com/yabwe/medium-editor/tree/master/src/js/extensions#geteditorelements](https://github.com/yabwe/medium-editor/tree/master/src/js/extensions#geteditorelements). Probably all my calls to 

`editor.origElements`

should be replaced with this function.
